example/example/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    url(r'', include('minicms.urls', namespace='minicms')),
    prefix_default_language=False)

minicms/urls.py
from django.conf.urls import url
from . import views

app_name = 'minicms'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^(?P<path>.+)/$', views.page, name='page'),
]

example/templates/base.html
{% load static i18n minicms %}<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}MiniCMS Example Project{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  {% block css %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
  {% endblock %}
</head>

<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'minicms:homepage' %}">
                MiniCMS Example
            </a>
            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarMenu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        
        <div id="navbarMenu" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{% url 'minicms:homepage' %}">Home</a>
                <a class="navbar-item" href="{% page_url 'contact' %}" id="contact_link">Contact</a>
                
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        More
                    </a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item">About</a>
                        <a class="navbar-item">Jobs</a>
                        <a class="navbar-item">Contact</a>
                        <hr class="navbar-divider">
                        <a class="navbar-item">Report an issue</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    {% block modal %}{% endblock modal %}
</body>
</html>